# Generated by Django 4.2.4 on 2024-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_products_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="size",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
